# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment_F' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assignment_F
  pod 'Cache'
  target 'Assignment_FTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Assignment_FUITests' do
    # Pods for testing
  end

end
